#!/usr/bin/env bash

VERSION="0.5"
DIR="wstat"
files="*.stat"
group=""     # "" = all
index_file="cst-all"
info_file="cst-all"

function show_help {
	echo ""
	echo "   CST index generator v$VERSION"
	echo "   https://github.com/bhaddacak/cst-kit"
	echo "   (This program makes use of GNU sed and gawk.)"
	echo ""
	echo "   Usage: ./genindex [-t <text-group>] [-v] [-h]"
	echo ""
	echo "   Before running this program stat data have to be present"
	echo "       in directory '$DIR'. If not, run this first:"
	echo ""
	echo "          ./genwordstat"
	echo ""
	echo "   Options:"
	echo "   -t <text-group>"
	echo "       Specify text group."
	echo "       If <text-group> is omitted, the entire '$DIR' will be processed."
	echo "       Available <text-group> are:"
	echo "          v  - The whole Vinaya"
	echo "          vm - The main texts in Vinaya"
	echo "          ve - The exegetical texts in Vinaya"
	echo "          s  - The whole Suttanta"
	echo "          sm - The main texts in Suttanta"
	echo "          se - The exegetical texts in Suttanta"
	echo "          a  - The whole Abhidhamma"
	echo "          am - The main texts in Abhidhamma"
	echo "          ae - The exegetical texts in Abhidhamma"
	echo "          m  - All main texts"
	echo "          e  - All exegetical texts"
	echo "   -v"
	echo "       Show the program's version."
	echo "   -h"
	echo "       Show this help."
	echo ""
}

while [[ -n "$1" ]]; do 
	case "$1" in 
		-t)
			shift 
			group="$1"
			;; 
		-v | --version)
			echo "CST index generator v$VERSION"
			exit
			;;
		-h | --help)
			show_help 
			exit 
			;; 
		*)
			show_help >&2 
			exit 1 
			;; 
	esac 
	shift 
done

if [ -d "$DIR" ]; then
	case "$group" in
		v | s | a)
			files="cst-$group*.stat"
			;;
		vm | ve | sm | se | am | ae)
			files="cst-$group-*.stat"
			;;
		m | e)
			files="cst-?$group-*.stat"
			;;
		*)
			files="*.stat"
			;;
	esac
	if [ -n "$group" ]; then
		index_file="cst-$group"
		info_file="cst-$group"
	fi
	totaldoc=$(ls $DIR/$files | wc -l)
	echo "Generating document info"
	info_file="${info_file}.info"
	gawk -v group="$group" -f geninfo.awk cstinfo.json > "$info_file"
	echo "'$info_file' created"
	echo "Generating index over $totaldoc documents"
	echo "... (This may take some minutes for the whole collection)"
	index_file="${index_file}_$totaldoc.index"
	gawk -v group="$group" -f genindex.awk $DIR/$files > "$index_file"
	echo "'$index_file' created"
else
	show_help
fi
