#!/usr/bin/env bash

VERSION="0.5"
OUTDIR="wstat"
keepcap="0" # keep capitalized terms, 0=no, 1=yes
target=""
sed_command='s/<\/\?[^>]\+>//g' # strip all tags

function show_help {
	echo ""
	echo "   CST word-stat generator v$VERSION"
	echo "   https://github.com/bhaddacak/cst-kit"
	echo "   (This program makes use of GNU sed and awk.)"
	echo ""
	echo "   Usage: ./genwordstat [-f <file>] [--keep-cap] [--exclude-notes] [-v] [-h]"
	echo ""
	echo "   The program generates stat files in directory '$OUTDIR' using"
	echo "       data in 'gz'."
	echo ""
	echo "   Options:"
	echo "   -f"
	echo "       Specify a <file> to be processed."
	echo "       If a file is not given, the entire 'gz' directory will be processed."
	echo "   --keep-cap"
	echo "       Retain all capitalized terms."
	echo "   --exclude-notes"
	echo "       Exclude redactional notes."
	echo "   -v"
	echo "       Show the program's version."
	echo "   -h"
	echo "       Show this help."
	echo ""
}

while [[ -n "$1" ]]; do 
	case "$1" in 
		-f)
			shift 
			target="$1"
			;; 
		--keep-cap)
			keepcap="1"
			;; 
		--exclude-notes)
			sed_command='s/<\/\?[^>]\+>//g;s/\[[^]]*\]//g' # strip all tags and notes
			;; 
		-v | --version)
			echo "CST word-stat generator v$VERSION"
			exit
			;;
		-h | --help)
			show_help 
			exit 
			;; 
		*)
			show_help >&2 
			exit 1 
			;; 
	esac 
	shift 
done

if [ -d "gz" ]; then
	[ -d "$OUTDIR" ] || mkdir "$OUTDIR"
else
	show_help >&2 
	exit 1
fi

function analyze {
	file=`basename $1`
	zcat $1 | sed $sed_command  | awk -v keepcap="$keepcap" -f genwordstat.awk | sort > "$OUTDIR/$file.stat"
}

if [ -z "$target" ]; then
	for file in gz/*.gz
	do
		echo "$file"
		analyze "$file"
	done
elif [ -e "$target" ]; then
	echo "$target"
	analyze "$target"	
fi

