#!/usr/bin/env bash

function validate {
	# number range, empty parens, undetected 'rend'
	zcat $1 | grep --color -i -e '^\([0-9]\+:\)\?[0-9]\{2,4\}-[0-9]\.' -e '^\([0-9]\+:\)\?[0-9]\{3,4\}-[0-9]\{2\}\.' -e '^\([0-9]\+:\)\?[0-9]\{4\}-[0-9]\{3\}\.' -e '( \*)' -e '\[ \*)\]' -e 'rend'
}

if [ -z "$1" ]; then
	# check entire directory
	for file in gz/*.gz
	do
		echo "[1;33m$file[0m"
		validate "$file"
	done
elif [ -e "$1" ]; then
	# check the file specified
	echo "[1;33m$1[0m"
	validate "$1"	
fi
